routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminCategoryController;
use App\Http\Controllers\Admin\AdminPostController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\PromoController;
use App\Http\Controllers\Admin\StatisticController;

Route::resources([
    'category' => AdminCategoryController::class,
    'category.post' => AdminPostController::class,
    'promo' => PromoController::class,
    'order' => OrderController::class,
],[
    'parameters' => [
        'category' => 'category:slug',
    ]
]);

Route::get('/statistic',[StatisticController::class,'statistic'])->name('statistic');
Route::post('/statistic/date',[StatisticController::class,'date'])->name('date');

routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Auth::routes();

Route::prefix('/category')->name('category.')->group( function () {
    Route::get('/', [CategoryController::class,'index'])->name('index');
    Route::get('/{category}', [CategoryController::class,'show'])->name('show');
    Route::get('/{category}/posts', [PostController::class,'index'])->name('post.index');
    Route::get('/{category}/{post}', [PostController::class,'show'])->name('post.show');
});
Route::get('/',ItemController::class)->name('home');
Route::prefix('/cart')->name('cart.')->group( function () {

    Route::post('/add',[CartController::class, 'addToCart'])->name('add');
    Route::delete('/remove/{cartproduct}',[CartController::class, 'remove'])->name('remove');
    Route::post('/promo',([CartController::class, 'promo']))->name('promo');
    Route::delete('/remove',[CartController::class, 'promoDelete'])->name('promo.delete');

});
Route::prefix('/order')->name('order.')->group( function () {

    Route::post('/create',[OrderController::class, 'create'])->name('create');
    Route::get('/show',[OrderController::class, 'show'])->name('show');

});

// Route::post('/add-to-cart',[CartController::class, 'addToCart'])->name('addToCart');
// Route::delete('/cartproduct/{cartproduct}',[CartController::class, 'remove'])->name('remove');
Route::get('/cart',[CartController::class, 'cart'])->name('cart');
Route::post('/checkpromo',[CartController::class, 'checkPromo'])->name('checkPromo');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Storage;

use Illuminate\Database\Eloquent\Casts\Attribute;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'preview',
        'description',
        'price',
        'image_path',
        'user_id',
        'category_id',
        'likes',
        'posted',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function cartProduct()
    {
        return $this->belongsTo(CartProduct::class, 'product_id', 'id');
    }

    public function orderProduct()
    {
        return $this->belongsTo(OrderProduct::class, 'product_id', 'id');
    }

    protected function imageSrc(): Attribute
    {
        return Attribute::make(
            get: fn ($value) =>  Storage::disk('public')->url($this->image_path),
        );
    }

    // protected function getImageSrcAttribute()
    // {
    //     return Storage::disk('public')->url($this->image_path);
    // }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index(Category $category)
    {
        $categories = Category::get();
        $posts = $category->posts()->latest('created_at')->simplePaginate(3);

        return view('posts.index', compact('posts', 'category','categories'));
    }

    public function show(Category $category, Post $post)
    {
        $categories = Category::get();
        return view('posts.show', compact('post', 'categories'));
    }
}

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('title', 'Create category')
@section('content')
<main id="main" class="main">
    <div class="pagetitle">
    <form method="POST" action="{{ route('admin.category.post.store', $category) }}" enctype="multipart/form-data" >
        @csrf
        <div class="form-group">


            <label for="image">Image:</label>
            <input type="file" class="form-control" name="image">
            @error('image')
                <p class="alert alert-danger">{{$message}}</p>
            @enderror


            <label for="title">Title:</label>
            <input type="string" class="form-control" placeholder="Enter name category" name="title">
            @error('title')
                <p class="alert alert-danger">{{$message}}</p>
            @enderror
          </div>
          <div class="form-group">
            <label for="preview">Preview:</label>
            <input type="string" class="form-control" placeholder="Enter name category" name="preview">
            @error('preview')
                <p class="alert alert-danger">{{$message}}</p>
            @enderror
          </div>
          <div class="form-group">
            <label for="description">Description:</label>
            <input type="string" class="form-control" placeholder="Enter name category" name="description">
            @error('description')
                <p class="alert alert-danger">{{$message}}</p>
            @enderror
          </div>


          <button type="submit" class="btn btn-default">Submit</button>
    </form>
    </div>
</main>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('title', 'Posts')
@section('content')
@include('parts.sidebar')
<main id="main" class="main">
    <div class="pagetitle">
        @foreach ($posts as $post)
            @include('parts.item', compact('post'))
        @endforeach
        {{ $posts->links() }}
    </div>
</main>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')
@section('title', 'Posts')
@section('content')
@include('parts.sidebar')
<main id="main" class="main">
    <div class="pagetitle">

<div class="card" style="width: 60rem">
    @if ($post->image_path)
    <div >
        <img style="width:400px;height:auto;" src="{{ $post->image_src }}" class="m-1 card-img-top" alt="img">
    </div>
    @endif

    <div class="card-body">

        <h5 class="card-title">{{ $post->title }}</h5>
        <p class="card-text">{{ $post->preview }}</p>
        <p class="card-text">Price: {{ $post->price }}$</p>

        {{-- <p class="card-text">author: {{ $post->user ? $post->user->name : 'без автора' }}</p> --}}
        {{-- @if ((auth()->user())) --}}
        <form action="{{ route('cart.add') }}" method="POST">
            @csrf
            <input type="hidden" name="product_id" value="{{ $post->id }}" />
            <div>Enter count</div>
            <input type="text" name='count' class="m-1 form-control" value="1" />

            <button type="submit" class="m-1 btn btn-primary">Add to cart</button>
        </form>
        {{-- @endif --}}
    </div>
    <a href="{{ route('category.index') }}" class="btn btn-primary">Go to categories</a>
  </div>

    </div>
</main>
@endsection