routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminCategoryController;
use App\Http\Controllers\Admin\AdminPostController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\PromoController;
use App\Http\Controllers\Admin\StatisticController;

Route::resources([
    'category' => AdminCategoryController::class,
    'category.post' => AdminPostController::class,
    'promo' => PromoController::class,
    'order' => OrderController::class,
],[
    'parameters' => [
        'category' => 'category:slug',
    ]
]);

Route::get('/statistic',[StatisticController::class,'statistic'])->name('statistic');
Route::post('/statistic/date',[StatisticController::class,'date'])->name('date');

routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Auth::routes();

Route::prefix('/category')->name('category.')->group( function () {
    Route::get('/', [CategoryController::class,'index'])->name('index');
    Route::get('/{category}', [CategoryController::class,'show'])->name('show');
    Route::get('/{category}/posts', [PostController::class,'index'])->name('post.index');
    Route::get('/{category}/{post}', [PostController::class,'show'])->name('post.show');
});
Route::get('/',ItemController::class)->name('home');
Route::prefix('/cart')->name('cart.')->group( function () {

    Route::post('/add',[CartController::class, 'addToCart'])->name('add');
    Route::delete('/remove/{cartproduct}',[CartController::class, 'remove'])->name('remove');
    Route::post('/promo',([CartController::class, 'promo']))->name('promo');
    Route::delete('/remove',[CartController::class, 'promoDelete'])->name('promo.delete');

});
Route::prefix('/order')->name('order.')->group( function () {

    Route::post('/create',[OrderController::class, 'create'])->name('create');
    Route::get('/show',[OrderController::class, 'show'])->name('show');

});

// Route::post('/add-to-cart',[CartController::class, 'addToCart'])->name('addToCart');
// Route::delete('/cartproduct/{cartproduct}',[CartController::class, 'remove'])->name('remove');
Route::get('/cart',[CartController::class, 'cart'])->name('cart');
Route::post('/checkpromo',[CartController::class, 'checkPromo'])->name('checkPromo');

resources/views/part/bodyscripts.blade.php
{{-- <script src="/vendor/apexcharts/apexcharts.min.js"></script>
<script src="/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="vendor/chart.js/chart.min.js"></script>
<script src="vendor/echarts/echarts.min.js"></script>
<script src="vendor/quill/quill.min.js"></script>
<script src="vendor/simple-datatables/simple-datatables.js"></script>
<script src=".."></script>
<script src="vendor/tinymce/tinymce.min.js"></script>
<script src="vendor/php-email-form/validate.js"></script> --}}

<!-- Template Main JS File -->
{{-- <script src="assets/js/main.js"></script> --}}
<script src="{{ asset('frontend/admin/js/app.js') }}" defer></script>

resources/views/part/footer.blade.php
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>Ecommerce</span></strong>. All Rights Reserved
    </div>

</footer><!-- End Footer -->

resources/views/part/head.blade.php
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">

<title>Dashboard - NiceAdmin Bootstrap Template</title>
<meta content="" name="description">
<meta content="" name="keywords">

<!-- Favicons -->
<link href="assets/img/favicon.png" rel="icon">
<link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

<!-- Google Fonts -->
<link href="https://fonts.gstatic.com" rel="preconnect">
<link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

<!-- Vendor CSS Files -->
<link href="{{ mix('frontend/admin/css/app.css') }}" rel="stylesheet">

resources/views/part/header.blade.php
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="{{route('home')}}" class="logo d-flex align-items-center">
            <span class="d-none d-lg-block">Ecommerce</span>
        </a>

    </div><!-- End Logo -->

    {{-- <div class="search-bar">
        <form class="search-form d-flex align-items-center" method="POST" action="#">
            <input type="text" name="query" placeholder="Search" title="Enter search keyword">
            <button type="submit" title="Search"><i class="bi bi-search"></i></button>
        </form>
    </div><!-- End Search Bar --> --}}
    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="/">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->
            @if ((session('order_id')&&!(Auth::check())))
            <li class="nav-item dropdown">
                <a class="nav-link nav-icon search-bar-toggle " href="{{ route('order.show') }}">
                    <i class="bi bi-bag"></i>
                </a>
            </li>
            @endif

            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="/" data-bs-toggle="dropdown">
                    <i class="bi bi-cart"></i>
                    <span class="badge bg-primary badge-number">{{ $cart->count }}</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <div>
                            @foreach ($cart->cartProducts as $item)

                  <div class="card mb-3">
                    <div class="card-body">
                      <div class="d-flex justify-content-between">
                        <div class="d-flex flex-row align-items-center">
                          <div>
                            @if ($item->post->image_path)

                            <img
                            src="{{ $item->post->image_src }}"
                            class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                            @endif
                          </div>
                          <div class="ms-3">
                            <h5>{{ $item->post->title }}</h5>
                            <p class="small mb-0">{{ $item->post->preview }}</p>
                          </div>
                        </div>
                        <div class="d-flex flex-row align-items-center">
                          <div style="width: 100px;">
                            <h5 class="fw-normal mb-0">
                                <form action="{{ route('cart.add') }}" method="POST">
                                    @csrf
                                    <div class="col-xs-3">
                                        <input type="hidden" name="product_id" value="{{ $item->product_id }}" />
                                        <input style="width: 50px;" type="number" name="count" value="{{$item->count}}" onchange="this.form.submit()"/>
                                    </div>
                                </form>

                            </h5>
                          </div>
                          <div style="width: 200px;">
                            <h5 class="mb-0">x1 - {{ $item->price }}$ <br> x{{$item->count}} - {{$item->sum }}$</h5>
                          </div>
                          <div style="width: 80px;">
                            <form action="{{ route('cart.remove', $item ) }}" method="POST">
                                @method('DELETE')
                                @csrf
                                <input class="btn btn-danger" type="submit" value="Delete" />
                            </form>
                          </div>
                          <a href="#!" style="color: #cecece;"><i class="fas fa-trash-alt"></i></a>
                        </div>
                      </div>
                    </div>
                  </div>
                  @endforeach
                        </div>
                    </li>
                    <li class="dropdown-header">
                        You have {{ $cart->count }} products in cart
                        <form method="POST" action="{{ route('order.create') }}">
                            @csrf
                            <input type="hidden" name="sum" value="{{ $cart->sum }}">
                            <input type="hidden" name="id" value="{{ $cart->id }}">
                            @if (!(auth()->check()))
                            <input placeholder="name" type="text" name="name" >
                            @endif
                            <button
                            @if($cart->sum == 0) @disabled(true)@endif

                                class="btn btn-primary btn-block btn-lg">
                                {{ $cart->sum }}$ Checkout <i class="fas fa-long-arrow-alt-right"></i>
                              </button>

                        </form>

                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->
            @if(Auth::check())


            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-chat-left-text"></i>
                    <span class="badge bg-success badge-number">3</span>
                </a><!-- End Messages Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
                    <li class="dropdown-header">
                        You have 3 new messages
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="{{ asset('/images/messages-1.jpg') }}" alt="" class="rounded-circle">
                            <div>
                                <h4>Maria Hudson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>4 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="{{ asset('/images/messages-2.jpg') }}" alt="" class="rounded-circle">
                            <div>
                                <h4>Anna Nelson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>6 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="{{ asset('/images/messages-3.jpg') }} alt="" class="rounded-circle">
                            <div>
                                <h4>David Muldon</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>8 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="dropdown-footer">
                        <a href="#">Show all messages</a>
                    </li>

                </ul><!-- End Messages Dropdown Items -->

            </li><!-- End Messages Nav -->

            <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="/profile"
                    data-bs-toggle="dropdown">
                    <img src="{{ asset('/images/profile-img.jpg') }}" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">{{Auth::user()->name}}</span>
                </a><!-- End Profile Iamge Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>{{Auth::user()->name}}</h6>
                        <span>Web Designer</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="/profile">
                            <i class="bi bi-person"></i>
                            <span>My Profile</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="/profile">
                            <i class="bi bi-gear"></i>
                            <span>Account Settings</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{{ route('order.show') }}">
                            <i class="bi bi-question-circle"></i>
                            <span>Orders</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST">
                            {{ csrf_field() }}
                            <button type="submit" class="dropdown-item d-flex align-items-center" ><i class="bi bi-box-arrow-right"></i>Logout</button>
                        </form>

                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->
            @else
                @if(!Route::is('login'))
                    <a class="dropdown-item  d-flex align-items-center" href="{{ route('login')}}">
                        <span>Login</span>
                    </a>
                @endif
                @if(!Route::is('register'))
                    <a class="dropdown-item d-flex align-items-center" href="{{ route('register')}}">
                        <span>Register</span>
                    </a>
                @endif
        @endif
        </ul>

    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

resources/views/part/orders.blade.php
@extends('layouts.app')
@section('title', 'Posts')
@section('content')
@include('parts.sidebar')
<main id="main" class="main">
    <div class="pagetitle">
        <section class="h-100">

            @foreach ($orders as $order)

            <section class="h-100 gradient-custom">
                <div class="container py-5 h-100">
                  <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-lg-10 col-xl-8">
                      <div class="card" style="border-radius: 10px;">
                        <div class="card-header px-4 py-5">
                          <h5 class="text-muted mb-0">Thanks for your Order, <span style="color: #a8729a;">{{$order->name}}</span>!</h5>
                        </div>
                        <div class="card-body p-4">
                            <div class="d-flex justify-content-between align-items-center mb-4">
                              <p class="lead fw-normal mb-0" style="color: #a8729a;">Receipt</p>
                              <p class="small text-muted mb-0">Order id : {{$order->id}}</p>
                            </div>

                        @foreach ($order->orderProducts as $item)

                            <div class="card shadow-0 border mb-4">
                              <div class="card-body">
                                <div class="row">
                                  <div class="col-md-2">

                                    @if ($item->product->image_path )
                                    <img src="{{ Storage::url( $item->product->image_path) }} "
                                      class="img-fluid" alt="Phone">
                                    @endif

                                  </div>
                                  <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                    <p class="text-muted mb-0">{{ $item->product->title }}</p>
                                  </div>
                                  <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                    <p class="text-muted mb-0 small">{{$item->product->preview}}</p>
                                  </div>

                                  <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                    <p class="text-muted mb-0 small">Qty: {{ $item->count }}</p>
                                  </div>
                                  <div class="col-md-2 text-center d-flex justify-content-center align-items-center">
                                    <p class="text-muted mb-0 small">{{ $item->price }}$</p>
                                  </div>
                                </div>
                                <hr class="mb-4" style="background-color: #e0e0e0; opacity: 1;">
                                <div class="row d-flex align-items-center">
                                  <div class="col-md-2">
                                    <p class="text-muted mb-0 small">Track Order</p>
                                  </div>
                                  <div class="col-md-10">
                                    <div class="progress" style="height: 6px; border-radius: 16px;">
                                      <div class="progress-bar" role="progressbar"
                                        style="width: 65%; border-radius: 16px; background-color: #a8729a;" aria-valuenow="65"
                                        aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <div class="d-flex justify-content-around mb-1">
                                      <p class="text-muted mt-1 mb-0 small ms-xl-5">{{ $order->status }}</p>
                                      <p class="text-muted mt-1 mb-0 small ms-xl-5">Delivered</p>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                        @endforeach


                          <div class="card shadow-0 border mb-4">


                          <div class="d-flex justify-content-between pt-2">
                            <p class="fw-bold mb-0">Order Details</p>
                          </div>



                          <div class="d-flex justify-content-between">
                            <p class="text-muted mb-0">Invoice Date : {{ $order->created_at }}</p>

                          </div>


                        <div class="card-footer border-0 px-4 py-5"
                          style="background-color: #a8729a; border-bottom-left-radius: 10px; border-bottom-right-radius: 10px;">
                          <h5 class="d-flex align-items-center justify-content-end text-white text-uppercase mb-0">Total
                            paid: <span class="h2 mb-0 ms-2">{{ $order->sum }}$</span></h5>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>

            @endforeach

          </section>


    </div>
</main>
@endsection