routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminCategoryController;
use App\Http\Controllers\Admin\AdminPostController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\PromoController;
use App\Http\Controllers\Admin\StatisticController;

Route::resources([
    'category' => AdminCategoryController::class,
    'category.post' => AdminPostController::class,
    'promo' => PromoController::class,
    'order' => OrderController::class,
],[
    'parameters' => [
        'category' => 'category:slug',
    ]
]);

Route::get('/statistic',[StatisticController::class,'statistic'])->name('statistic');
Route::post('/statistic/date',[StatisticController::class,'date'])->name('date');

routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Auth::routes();

Route::prefix('/category')->name('category.')->group( function () {
    Route::get('/', [CategoryController::class,'index'])->name('index');
    Route::get('/{category}', [CategoryController::class,'show'])->name('show');
    Route::get('/{category}/posts', [PostController::class,'index'])->name('post.index');
    Route::get('/{category}/{post}', [PostController::class,'show'])->name('post.show');
});
Route::get('/',ItemController::class)->name('home');
Route::prefix('/cart')->name('cart.')->group( function () {

    Route::post('/add',[CartController::class, 'addToCart'])->name('add');
    Route::delete('/remove/{cartproduct}',[CartController::class, 'remove'])->name('remove');
    Route::post('/promo',([CartController::class, 'promo']))->name('promo');
    Route::delete('/remove',[CartController::class, 'promoDelete'])->name('promo.delete');

});
Route::prefix('/order')->name('order.')->group( function () {

    Route::post('/create',[OrderController::class, 'create'])->name('create');
    Route::get('/show',[OrderController::class, 'show'])->name('show');

});

// Route::post('/add-to-cart',[CartController::class, 'addToCart'])->name('addToCart');
// Route::delete('/cartproduct/{cartproduct}',[CartController::class, 'remove'])->name('remove');
Route::get('/cart',[CartController::class, 'cart'])->name('cart');
Route::post('/checkpromo',[CartController::class, 'checkPromo'])->name('checkPromo');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    use HasFactory;

    protected $perPage = 20;

    protected $fillable = [
        'name',
        'slug',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($category){
            $category->slug = Str::slug($category->name);
        });
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }


}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;
use Phpfastcache\Helper\Psr16Adapter;

use App\Models\Category;

class CategoryController extends Controller
{
    public function index()
    {

        // $instagram = InstagramScrapper::withCredentials(env('INSTA_USER'), env('INSTA_PASS'), new PSRCacheInterface());
        // $media = $instagram->getAccount('gigaprog');
        //$nonPrivateAccountMedias = $instagram->getMediasByUrl('https://www.instagram.com/p/CejJqPXqpnP/');
        //$media = $instagram->getMediaById('2856169073822833103');
        // dd($media);
        // $categories = Category::withCount('posts')
        //                     ->with('posts.user')
        //                     ->latest()
        //                     ->simplePaginate(3);
        // return view('categories.index',compact('categories'));
    }

    public function show(Category $category)
    {
        return view('categories.show', compact('category'));
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Create category')
@section('content')
@include('admin.components.sidebar')
<main id="main" class="main">
    <div class="pagetitle">
        <form method="POST" action=" {{route('admin.category.store') }}">

            @csrf
            <div class="row mb-3">
                <label for="name" class="col-sm-2 col-form-label">Category:</label>
                    <div class="col-sm-10">
                        <input type="string" class="form-control" id="category" placeholder="Enter name category" name="name">
                            @error('name')
                                <p class="alert alert-danger">{{$message}}</p>
                            @enderror
                    </div>
                </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                </div>
        </form>
    </div>
</main>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Posts')
@section('content')
@include('admin.components.sidebar')
<main id="main" class="main">
    <div class="pagetitle">
        <a class="btn btn-primary" href="{{route('admin.category.create') }}" role="button">Create Category</a>
         <table class="table">
            <thead>
                <tr>
                  <th scope="col">Id</th>
                      <th scope="col">Category</th>
                       <th scope="col">Item Count</th>
                      <th scope="col">Created at</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($categories as $category)
                    <tr>
                        <td>{{$category->id}}</td>
                        <td>{{$category->name}}</td>
                        <td>{{$category->posts_count}}</td>
                        <td>{{$category->created_at}}</td>
                        <td>
                                <a class="btn btn-primary " href="{{route('admin.category.post.index',$category)}}">
                                    <span>Go to category</span>
                                </a>
                        </td>
                        <td>
                            <form action="{{ route('admin.category.destroy', $category) }}" method="post">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>

        </table>
        {{ $categories->links() }}
    </div>
</main>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layouts.app')
@section('title', 'Posts')
@section('content')
@include('admin.components.sidebar')
    <div class="container">
        <h1>Category name: {{$category->name}}</h1>
    </div>
@endsection

resources/views/admin/categories/update.blade.php
@extends('admin.layouts.app')
@section('title', 'Post update')
@section('content')
@include('admin.components.sidebar')
<main id="main" class="main">
    <div class="pagetitle">
        <form method="POST" action=" {{route('admin.category.update', $category) }}">
            @method('PUT')
            @csrf
            <div class="row mb-3">
                <label for="name" class="col-sm-2 col-form-label">Category:</label>
                    <div class="col-sm-10">
                        <input type="string" class="form-control" value="{{ $category->name }}" id="category" placeholder="Enter name category" name="name" >
                            @error('name')
                                <p class="alert alert-danger">{{$message}}</p>
                            @enderror
                    </div>
                </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit Form</button>
                </div>
        </form>
    </div>
</main>
@endsection